language: go

sudo: required
dist: trusty

go:
  - "1.11.x"
  - "1.10.x"
  - "1.9.x"
  - "tip"

env:
- LIBVIPS=7.42
- LIBVIPS=8.2
- LIBVIPS=8.3
- LIBVIPS=8.4
- LIBVIPS=8.5
- LIBVIPS=8.6
- LIBVIPS=8.7
- LIBVIPS=master

matrix:
  allow_failures:
  - env: LIBVIPS=7.42
  - env: LIBVIPS=8.2
  - env: LIBVIPS=8.3
  - env: LIBVIPS=master
  - go: 1.8.x

cache: apt

addons:
  apt:
    packages:
    - gobject-introspection
    - gtk-doc-tools
    - libcfitsio3-dev
    - libfftw3-dev
    - libgif-dev
    - libgs-dev
    - libgsf-1-dev
    - libmatio-dev
    - libopenslide-dev
    - liborc-0.4-dev
    - libpango1.0-dev
    - libpoppler-glib-dev
    - libwebp-dev

before_install:
  - wget https://github.com/libvips/libvips/archive/$LIBVIPS.zip
  - unzip $LIBVIPS
  - cd libvips-$LIBVIPS
  - test -f autogen.sh && ./autogen.sh || ./bootstrap.sh
  - >
    CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0
    ./configure
    --disable-debug
    --disable-dependency-tracking
    --disable-introspection
    --disable-static
    --enable-gtk-doc-html=no
    --enable-gtk-doc=no
    --enable-pyvips8=no
    --without-orc
    --without-python
    $1
  - make
  - sudo make install
  - sudo ldconfig

script:
  - cd ..
  - go test -v -race -covermode=atomic

deploy:
- provider: script
  script: docker run -it -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
    -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG -e JENKINS_BUILD_BRANCH=$TRAVIS_BRANCH
    p1hub/p1jenkinstrigger
  on:
    branch: master

notifications:
  slack:
    secure: L2pA6eBn13z9FXI4Ef/5hZvaBC+lXbGJL8tj4QK5kJ0G5AuLUd+yj7BH76ZcFiYB7gEnWMCxUAoHONFXi46Rew7kPIsb7IjdF4+++/o5sBfdudmV0mnhBt0BcFpFcybUlODqZh4QccU/Xe16A3O1GtmvEF4H5pABTdo+pCc0Y2QxdVSr8FOHeNIFxx/sN9bSPenUAq3S2kbU+RaJKmVy+STSiqeKKeVg9tHDr3ePXGVxzz7IAiJiQTijflxEHbzcFAWPfaCsQ+iv7Wkk7AJyuaaQbrAKqJF49cyQULc7x7lL7WsRcBXJE22bpd1jVRT62c03fyeQYNiTTXk2no6jVL05+/YUGuv0b+vq5L45nWkT5F2LKYGrLRnE/cHKZWEZXL/PRWIYaDF4c6S9w/Fg/FSqY1m3LWcItkeasgSZF9CwEWP/R4inDdLoIl36GwoUkEIlSwkmUeaKZN+pSAMD9OT304M7NrBIEotrWNu/SxXq8Coe5MTFNgERtszxhfSJz78N2BOIPk/mbyCONdT0svtJfOxDxtLlyyu5/TH4/Ez+2zj543rdr2LVlUyySP3lPaB5hKOUnJObwdEC/WmR2EFznqScMFQ+wUMbwoKrr/2KVuCby465SGpt+YqQduSpHy1qTD+nbWegwRspabug5Auw+qJR/A5mYYnqkeTNnrk=
