version: "3"

services:
  imaginary:
    build: .
    volumes:
      - images:/mnt/data
    ports:
      - "9000:9000"
    environment:
        PORT: 9000
        DEBUG: "*"
    command: -enable-url-source -mount /mnt/data -cors -concurrency 10 -max-allowed-size 10485760 -c /application/etc/local.yaml
volumes:
  images:
    external: true

